### ISSUE TITLE
not shown in layout file.

### ISSUE THREAD

**Issue by olissongs** [cinghie/yii2-cookie-consent#4]
Hi,

i put it in the main layout file

in top
```
use cinghie\cookieconsent\widgets\CookieWidget;
```

before end body
```
 <?= CookieWidget::widget([ 
 	'message' => 'Diese Website nutzt Cookies, um bestmögliche Funktionalität bieten zu können.',
    	'dismiss' => 'Ok, verstanden',
    	'learnMore' => 'Mehr Infos',
 	'link' => '../datenschutz',
    	'theme' => 'dark-bottom',
]); ?>
```
generates this output:
```
<script src="/assets/2bde300b/cookieconsent.min.js"></script>
<script type="text/javascript">jQuery(document).ready(function () {
window.cookieconsent_options = { message: 'Diese Website nutzt Cookies, um bestmögliche Funktionalität bieten zu können.', dismiss: 'Ok, verstanden', learnMore: 'Mehr Infos', link: '../datenschutz', theme: 'dark-bottom', container: '', path: '/', expiryDays: 365 };
});</script>
```

but it is not shown, if i put this line in head
```
 <script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>
```
then its working, but i dont't want to download additional things.

so what going wrong?
i'm using yii2 2.0.10 and php 7 under ubuntu 16.04

**Comment by chris68** [comment]
Same problem for me. Seems that an non-fitting js implementation is used in this yii2 setup.

I also added
 <script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>
as a quick hack.

**Comment by chris68** [comment]
Even the  version 2.0.0 of the actual js implementation is still working.

But if a force my composer file to use the beta version "cinghie/yii2-cookie-consent": "v1.4.4b" composer does not find the version 2.0.0 of the respective bower asset. 

It only indicates the a version 3.0.3 und 3.0.2 exists. Strange...

So I needed to stick to the patch.

**Comment by chris68** [comment]
The Version 3.x of the respective Java implementation introduced a completely new initialization procedure. You can see it when you use the setup in https://cookieconsent.insites.com.

Since this yii2 plugin did not update to 3.0 logic I now used to following direct code
```
/*
 * Register cooking consent according to https://cookieconsent.insites.com
 */
$this->registerCssFile('https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css');
$this->registerJsFile('https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js');
    $codeJs = '
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#eaf7f7",
      "text": "#5c7291"
    },
    "button": {
      "background": "#56cbdb",
      "text": "#ffffff"
    }
  },
  "content": {
    "message": "Diese Webseite nutzt Cookies, für deren Einsatz die EU ihr Einverständnis verlangt",
    "dismiss": "Verstanden",
    "link": "Details",
    "href": "'.Url::to(['site/privacy']).'"
  }
})});
';
$this->registerJs($codeJs);

```

Maybe it helps for all other users having the same problem

**Comment by cinghie** [comment]
@olissongs @chris68 the new version fix the bower asset problem specifying the cookieconsent 2 version. 
In next versions i will upgrade the bower assets to version 3
