### ISSUE TITLE
Internet Explorer 11 - cookie config reverts to default

### ISSUE THREAD

**Issue by ghost** [cinghie/yii2-cookie-consent#7]
Hello, can you please check that this works in IE 11 (or any other)? 

It seems that the default configuration is used in IE, whereas in Chrome and Firefox it works correctly.

**Comment by jevansloreto** [comment]
I have the same problem in Chrome - it worked once, now all it gives is the default version. I can see the JS to call the plugin added to the page source, but it looks like it is totally ignored:


<script src="/assets/4b3a177a/cookieconsent.min.js"></script>
--
  | <script>jQuery(function ($) {
  | window.cookieconsent_options = { message: 'This website uses cookies to ensure the best experience.', dismiss: 'Do not show again', learnMore: 'More info', link: '/Privacy_and_Cookies_Policy.pdf', theme: 'dark-bottom', container: '', path: '/', expiryDays: 365 };
  | });</script>

**Comment by ghost** [comment]
A workaround for me was to add the exact same code at the head of the html (in base.php). For some reason this worked:

SCRIPT;

```
$consentJs = <<< 'SCRIPT'
window.cookieconsent_options = { 
    message: 'This website uses cookies to ensure you get the best experience on our websites. Find out more on', 
    dismiss: 'Close', 
    learnMore: 'how we use cookies.', 
    link: 'https://www.echa.europa.eu/legal-notice#cookies', 
    theme: 'css/cookie-consent.css', container: '', 
    path: '/', 
    expiryDays: 365 
}
SCRIPT;

$this->registerJs($consentJs, View::POS_HEAD);
```

**Comment by jevansloreto** [comment]
Thanks. I gave up on this widget and just installed the latest version of cookie consent directly. It looks like version 3 is a complete rebuild - the syntax for configuring it is totally different.

**Comment by cinghie** [comment]
Last version 1.4.6 fix the bug on some browser; that module use version 2.0 of Cookie Consent.

I have programmed the development of the new version that implements the new version 3.0 of Cookie Consent as soon as possible
