### ISSUE TITLE
The options set for cookie-consent are not used in firefox

### ISSUE THREAD

**Issue by nagyt234** [cinghie/yii2-cookie-consent#9]
Even if I use other options at calling th widget as the defaults, the default cookie consent dialog appears. Interestingly it works with Chrome, but not with Firefox. It is about a timing problem.
The problem is that the JS code snippet in _views/cookieWidget.php_ is registered with no options, i.e. in POS_READY. It called to late, the cookie-consent dialog is already initialized. It should be registered like this:
`$this->registerJs($codeJS, \yii\web\View::POS_BEGIN);`
So works perfectly.

**Comment by titusvk** [comment]
> Even if I use other options at calling th widget as the defaults, the default cookie consent dialog appears. Interestingly it works with Chrome, but not with Firefox. It is about a timing problem.
> The problem is that the JS code snippet in _views/cookieWidget.php_ is registered with no options, i.e. in POS_READY. It called to late, the cookie-consent dialog is already initialized. It should be registered like this:
> `$this->registerJs($codeJS, \yii\web\View::POS_BEGIN);`
> So works perfectly.

No, its $this->registerJs($codeJS, \yii\web\View::POS_END);

**Comment by cinghie** [comment]
Hi @titusvk,

thanks for your solution; I implemented that in the new version 1.4.6.
